### ISSUE TITLE
arrange network

### ISSUE THREAD

**Issue by xiedidan** [xiedidan/luna-network#10]

**Comment by xiedidan** [comment]
please describe this issue
we should create resnet python creator ASAP

**Comment by xiedidan** [comment]
we have finished network as below:
1. minimal resNeXt with group convolution : only one unit（3-layer convolution）
2. 50-layer resNet
3. 50-layer resNeXt with group convolution 
4. minimal resNeXt with no-group convolution : only one unit（3-layer convolution）

**Comment by xiedidan** [comment]
we should create another 15 unit just like the first unit. 
A 50-layer resNeXt has 16 unit.

**Comment by bettyeats** [comment]
we have finished network as below:

minimal resNeXt with group convolution : only one unit（3-layer convolution）
50-layer resNet
50-layer resNeXt with group convolution
minimal resNeXt with no-group convolution : only one unit（3-layer convolution）

**Comment by bettyeats** [comment]
we should create another 15 unit just like the first unit.
A 50-layer resNeXt has 16 unit.

**Comment by xiedidan** [comment]
Still don't know the propose of this issue, closing it since nothing seems to be done.
