### ISSUE TITLE
ResNet running too fast

### ISSUE THREAD

**Issue by xiedidan** [xiedidan/luna-network#3]

**Comment by xiedidan** [comment]
3.8\*10\^9 FLOPs for 50-layer resNet in paper "deep residual learning for image recognition". 4.1\*10\^9 FLOPs for 50-layer resNet as well as 4.2\*10\^9 FLOPs for 50-layer resNeXt in paper "aggregated residual transformations for deep neural networks"

**Comment by bettyeats** [comment]
3.8\*10\^9 FLOPs for 50-layer resNet in paper "deep residual learning for image recognition". 
4.1\*10\^9 FLOPs for 50-layer resNet as well as 4.2\*10\^9 FLOPs for 50-layer resNeXt in paper "aggregated residual transformations for deep neural networks"

**Comment by bettyeats** [comment]
224\*224 image VS. 64\*64\*64 image.
our image is five times as big as the image of paper.

**Comment by xiedidan** [comment]
That still doesn't explain the gap between 3.8 * 5 * 10^9 flops and 9 * 10^12 flops.  
Our computing power is more than 450 times larger than problem scale.

**Comment by xiedidan** [comment]
Any comment on this?

**Comment by xiedidan** [comment]
9 * 10^12 flops stands for what?

**Comment by bettyeats** [comment]
9 * 10^12 flops stands for what?

**Comment by xiedidan** [comment]
gtx1080 has nearly 9T Flops fp32 computing power per sec
that's 9 * 10 ^ 12 flops/s

**Comment by bettyeats** [comment]
16 unit calculate：
224\*224\*81\*64+
224\*224\*（2\*2\*128+4\*4\*128\*32+2\*2\*256+2\*2\*256）+
224\*224\*（2\*2\*128+4\*4\*128\*32+2\*2\*256）+
224\*224\*（2\*2\*128+4\*4\*128\*32+2\*2\*256）+
224\*224\*（2\*2\*256+5\*5\*256\*32+2\*2\*512+3\*3\*512）+
224\*224\*（2\*2\*256+4\*4\*256\*32+2\*2\*512）+
224\*224\*（2\*2\*256+4\*4\*256\*32+2\*2\*512）+
224\*224\*（2\*2\*256+4\*4\*256\*32+2\*2\*512）+
224\*224\*（2\*2\*512+5\*5\*512\*32+2\*2\*1024+3\*3\*1024）+
224\*224\*（2\*2\*512+4\*4\*512\*32+2\*2\*1024）+
224\*224\*（2\*2\*512+4\*4\*512\*32+2\*2\*1024）+
224\*224\*（2\*2\*512+4\*4\*512\*32+2\*2\*1024）+
224\*224\*（2\*2\*512+4\*4\*512\*32+2\*2\*1024）+
224\*224\*（2\*2\*512+4\*4\*512\*32+2\*2\*1024）+
224\*224\*（2\*2\*1024+5\*5\*1024\*32+2\*2\*2048+3\*3\*2048)+
224\*224\*（2\*2\*1024+4\*4\*1024\*32+2\*2\*2048）+
224\*224\*（2\*2\*1024+4\*4\*1024\*32+2\*2\*2048）
= 2.26\*10^11
maybe calcute conv without　stride,

224\*224\*（49\*64）+     
224\*224\*（1\*1\*128+3\*3\*128\*32+1\*1\*256+1\*1\*256）+    
224\*224\*（1\*1\*128+3\*3\*128\*32+1\*1\*256）+   
224\*224\*（1\*1\*128+3\*3\*128\*32+1\*1\*256）+   
224\*224\*（1\*1\*256+3\*3\*256\*32+1\*1\*512+1\*1\*512）+    
224\*224\*（1\*1\*256+3\*3\*256\*32+1\*1\*512）+     
224\*224\*（1\*1\*256+3\*3\*256\*32+1\*1\*512）+      
224\*224\*（1\*1\*256+3\*3\*256\*32+1\*1\*512）+     
224\*224\*（1\*1\*512+3\*3\*512\*32+1\*1\*1024+1\*1\*1024）+   
224\*224\*（1\*1\*512+3\*3\*512\*32+1\*1\*1024）+   
224\*224\*（1\*1\*512+3\*3\*512\*32+1\*1\*1024）+    
224\*224\*（1\*1\*512+3\*3\*512\*32+1\*1\*1024）+    
224\*224\*（1\*1\*512+3\*3\*512\*32+1\*1\*1024）+     
224\*224\*（1\*1\*512+3\*3\*512\*32+1\*1\*1024）+     
224\*224\*（1\*1\*1024+3\*3\*1024\*32+1\*1\*2048+1\*1\*2048)+    
224\*224\*（1\*1\*1024+3\*3\*1024\*32+1\*1\*2048）+    
224\*224\*（1\*1\*1024+3\*3\*1024\*32+1\*1\*2048）   
   
＝10\*10^10

ｔｈｅ　ｒｅｓｕｌｔ　ｉｓ　ｍｕｃｈ　ｔｉｍｅｓ　ｔｈａｎ　４．２＊１０＾９
ｓｏ，ｃａｃｕｌａｔｅ　ａｓ　ｂｅｌｏｗ：
224\*224\*（1\*1\*128+3\*3\*128+1\*1\*256+1\*1\*256）+    
224\*224\*（1\*1\*128+3\*3\*128+1\*1\*256）+   
224\*224\*（1\*1\*128+3\*3\*128+1\*1\*256）+   
224\*224\*（1\*1\*256+3\*3\*256+1\*1\*512+1\*1\*512）+    
224\*224\*（1\*1\*256+3\*3\*256+1\*1\*512）+     
224\*224\*（1\*1\*256+3\*3\*256+1\*1\*512）+      
224\*224\*（1\*1\*256+3\*3\*256+1\*1\*512）+       
224\*224\*（1\*1\*512+3\*3\*512+1\*1\*1024+1\*1\*1024）+   
224\*224\*（1\*1\*512+3\*3\*512+1\*1\*1024）+   
224\*224\*（1\*1\*512+3\*3\*512+1\*1\*1024）+  
224\*224\*（1\*1\*512+3\*3\*512+1\*1\*1024）+  
224\*224\*（1\*1\*512+3\*3\*512+1\*1\*1024）+
224\*224\*（1\*1\*512+3\*3\*512+1\*1\*1024）+  
224\*224\*（1\*1\*1024+3\*3\*1024+1\*1\*2048+1\*1\*2048)+    
224\*224\*（1\*1\*1024+3\*3\*1024+1\*1\*2048）+    
224\*224\*（1\*1\*1024+3\*3\*1024+1\*1\*2048）   
=4.7*10^9

**Comment by bettyeats** [comment]
ｓｏ　ｏｕｒ　ｎｅｔｗｏｒｋ　ｃａｃｕｌａｔｅ　ａｓ　ｂｅｌｏｗ：
64\*64\*64*［（1\*1\*128+3\*3\*128+1\*1\*256+1\*1\*256）+    
（1\*1\*128+3\*3\*128+1\*1\*256）+   
（1\*1\*128+3\*3\*128+1\*1\*256）+   
（1\*1\*256+3\*3\*256+1\*1\*512+1\*1\*512）+    
（1\*1\*256+3\*3\*256+1\*1\*512）+     
（1\*1\*256+3\*3\*256+1\*1\*512）+      
（1\*1\*256+3\*3\*256+1\*1\*512）+       
（1\*1\*512+3\*3\*512+1\*1\*1024+1\*1\*1024）+   
（1\*1\*512+3\*3\*512+1\*1\*1024）+   
（1\*1\*512+3\*3\*512+1\*1\*1024）+  
（1\*1\*512+3\*3\*512+1\*1\*1024）+  
（1\*1\*512+3\*3\*512+1\*1\*1024）+
（1\*1\*512+3\*3\*512+1\*1\*1024）+  
（1\*1\*1024+3\*3\*1024+1\*1\*2048+1\*1\*2048)+    
（1\*1\*1024+3\*3\*1024+1\*1\*2048）+    
（1\*1\*1024+3\*3\*1024+1\*1\*2048）  ］
=94464\*64\*64\*64
=2.4\*10^10

ｃｏｎｃｌｕｓｉｏｎ　ｉｓ，ｔｈｅ　ＦＬＯＰｓ　ｉｓ　ｓｏ　ｓｍａｌｌ．Our computing power is more than ３７５ times larger than problem scale.

**Comment by bettyeats** [comment]
So you have already confirmed the calculation in the paper is correct.
Considering we have spent so much time on this little simple problem, I don't recommend to do further research on this.

**Comment by xiedidan** [comment]
Closing this issue since we'll directly test resnet implementation.
