### ISSUE TITLE
vnet deploy

### ISSUE THREAD

**Issue by xiedidan** [xiedidan/luna-network#5]

**Comment by bettyeats** [comment]
deploy flow:
1. run network deploy (scan all CTs)
2. concat all the slices produced by step 1
3. notate

**Comment by xiedidan** [comment]
- [x] vnet output - results[1] - results[0], set item to 0 if item < 0
- [x] concat, could be selected
- [x] lung mask filter - before blob detection to reduce computation
- [x] blob detection
- [x] get radius
- [x] convert to world coord
- [x] write to csv

**Comment by xiedidan** [comment]
Done.
